# Dockerfile.frontend
FROM node:18

WORKDIR /app

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
ENV NODE_ENV=development
RUN npm install

COPY . .

CMD ["npm", "run", "dev:frontend"]