version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    command: npm run dev:backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app
    command: npm run dev:frontend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    env_file:
      - .env